  # SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123
  host: 127.0.0.1
  port: 3306
  timeout: 5000

development:
  <<: *default
  database: scheduled_tweets_development
  encoding: utf8

test:
  <<: *default
  database: scheduled_tweets_test
  encoding: utf8

production:
  <<: *default
  database: scheduled_tweets_production
  encoding: utf8
